ping-all: 
    echo "Ping all instances inside inventory.ini " 
    ansible -i inventory.ini \
        all -m ping 

nfs-server: 
    echo "Setting up NFS Server..... 🔥" 
    ansible-playbook -i inventory.ini \
        playbooks/nfs-server.yaml 

nfs-client: 
    echo "Setting up NFS Client ... " 
    ansible-playbook -i inventory.ini \
        playbooks/nfs-client.yaml 

nfs-all: 
    echo "Setting up NFS Client & Server ... " 
    ansible-playbook -i inventory.ini \
        playbooks/nfs-main.yaml 